apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q8kl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q8kl
    app.kubernetes.io/part-of: ci10t-777-0057-app
  name: devfile-sample-q8kl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-q8kl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-q8kl
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0057-tenant/ci10t-777-0057-app/devfile-sample-q8kl@sha256:02a6525cf63212fb659fdfb7f08fd8e3b8ad84793a625fa8d072400974a1b3d0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
